# Configuration Fly.io pour Nutritio
app = "nutritio-app"
primary_region = "cdg"  # Paris

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3006"
  NODE_ENV = "production"
  AUTH_TRUST_HOST = "true"
  DATABASE_URL = "file:/app/prisma/dev.db"

[[services]]
  internal_port = 3006
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/api/auth/session"

[mounts]
  source = "nutritio_data"
  destination = "/app/prisma"

